export const SankeyData = [
  ["From", "To", "Weight"],
  ["Brazil", "Portugal", 5],
  ["Brazil", "France", 1],
  ["Brazil", "Spain", 1],
  ["Brazil", "England", 1],
  ["Canada", "Portugal", 1],
  ["Canada", "France", 5],
  ["Canada", "England", 1],
  ["Mexico", "Portugal", 1],
  ["Mexico", "France", 1],
  ["Mexico", "Spain", 5],
  ["Mexico", "England", 1],
  ["USA", "Portugal", 1],
  ["USA", "France", 1],
  ["USA", "Spain", 1],
  ["USA", "England", 5],
  ["Portugal", "Angola", 2],
  ["Portugal", "Senegal", 1],
  ["Portugal", "Morocco", 1],
  ["Portugal", "South Africa", 3],
  ["France", "Angola", 1],
  ["France", "Senegal", 3],
  ["France", "Mali", 3],
  ["France", "Morocco", 3],
  ["France", "South Africa", 1],
  ["Spain", "Senegal", 1],
  ["Spain", "Morocco", 3],
  ["Spain", "South Africa", 1],
  ["England", "Angola", 1],
  ["England", "Senegal", 1],
  ["England", "Morocco", 2],
  ["England", "South Africa", 7],
  ["South Africa", "China", 5],
  ["South Africa", "India", 1],
  ["South Africa", "Japan", 3],
  ["Angola", "China", 5],
  ["Angola", "India", 1],
  ["Angola", "Japan", 3],
  ["Senegal", "China", 5],
  ["Senegal", "India", 1],
  ["Senegal", "Japan", 3],
  ["Mali", "China", 5],
  ["Mali", "India", 1],
  ["Mali", "Japan", 3],
  ["Morocco", "China", 5],
  ["Morocco", "India", 1],
  ["Morocco", "Japan", 3],
];

export const BarData = [
  ["Day", "Sales"],
  ["S", 10000],
  ["M", 3500],
  ["T", 5600],
  ["W", 6200],
  ["T", 4000],
  ["F", 2030],
  ["S", 6830],
];

export const BarOptions = {
  chart: {
    title: "kWh 3,701 -20%",
    // subtitle: "Sales, Expenses, and Profit: 2014-2017",
  },
  animation: {
    startup: true,
    easing: "linear",
    duration: 1500,
  },
  enableInteractivity: false,
};

export const GeoData = [
  ["Country", "Popularity"],
  ["Germany", 200],
  ["United States", 300],
  ["Brazil", 400],
  ["Canada", 500],
  ["France", 600],
  ["RU", 700],
];

export const ComposeData = [
  {
    name: "Page A",
    uv: 590,
    pv: 800,
    amt: 1400,
  },
  {
    name: "Page B",
    uv: 868,
    pv: 967,
    amt: 1506,
  },
  {
    name: "Page C",
    uv: 1397,
    pv: 1098,
    amt: 989,
  },
  {
    name: "Page D",
    uv: 1480,
    pv: 1200,
    amt: 1228,
  },
  {
    name: "Page E",
    uv: 1520,
    pv: 1108,
    amt: 1100,
  },
  {
    name: "Page F",
    uv: 1400,
    pv: 680,
    amt: 1700,
  },
];
